# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    #steps:
    #  - name: Hello
    #    uses: dagger/dagger-for-github@v5
    #    with:
    #      verb: call 
    #      module: github.com/shykes/daggerverse/hello
    #      args: -d hello --greeting Hola --name Jeremy
    #      cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Local
        uses: dagger/dagger-for-github@v5
        with:
          args: container-echo --string-arg "Hello, Dagger!" stdout
